#/*
#* Copyright (c) 2022 Gouvernement du Québec
#* Auteur: Julio Cesar Torres 
#* SPDX-License-Identifier: LiLiQ-R-v.1.1
#* License-Filename: /LICENSE
#*/
##############################################################
# Requetes http pour l'émeteur d'attestations d'accès virtuel
##############################################################
# Avant usage, il faut renseigner les champs X-API-Key des 
# endpoints qui seront utilisés. 
# 
### Définition des variables globales 
@hostname = http://localhost:3000
@id = 10

# ============================================================================
#    Entity: Coffee
#    Endpoint: /coffee
# ============================================================================

####
#### Selects all coffees 
#### 
GET {{hostname}}/coffees HTTP/1.1
X-API-Key: 
Content-Type: application/json


####
#### Selects all coffees with pagination
#### 
GET {{hostname}}/coffees?limit=2&offset=4 HTTP/1.1
X-API-Key: 
Content-Type: application/json


####
#### Selects a coffee identified by id 
#### 
GET {{hostname}}/coffees/{{id}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Create a new coffee 
#### 
POST {{hostname}}/coffees HTTP/1.1
X-API-Key: 
Content-Type: application/json

{
    "name": "Cafe Caesar # 55", 
    "brand": "Cafe Romano", 
    "flavors": ["merengue", "coffee", "chocolate", "orange", "shite", "merda"]
}

####
#### Create a new batch of coffees 
#### 
POST {{hostname}}/coffees HTTP/1.1
X-API-Key: 
Content-Type: application/json

[  
  {
      "name": "Cafe Caesar # 1", 
      "brand": "Cafe Romano", 
      "flavors": ["coffee", "chocolate" ]
  },
  {
      "name": "Cafe Caesar # 2", 
      "brand": "Cafe Romano", 
      "flavors": ["coffee" ]
  },
  {
      "name": "Cafe Caesar # 3", 
      "brand": "Cafe Romano", 
      "flavors": ["coffee", "dark roast" ]
  },
    {
      "name": "Cafe Caesar # 4", 
      "brand": "Cafe Romano", 
      "flavors": ["coffee", "torrefaction foncée" ]
  },
  {
      "name": "Cafe Caesar # 5", 
      "brand": "Cafe Romano", 
      "flavors": ["coffee" ]
  },
  {
      "name": "Cafe Caesar # 6", 
      "brand": "Cafe Romano", 
      "flavors": ["coffee", "orange" ]
  },
  {
      "name": "Cafe African #1", 
      "brand": "Africa Roast", 
      "flavors": ["coffee", "kenyan" ]
  },
  {
      "name": "Cafe African #2", 
      "brand": "Africa Roast", 
      "flavors": ["coffee", "ethiopia" ]
  },
  {
      "name": "Cafe African #3", 
      "brand": "Africa Roast", 
      "flavors": ["coffee", "ethiopia", "kenyan" ]
  },
  { 
      "name": "Cafe African #4", 
      "brand": "Africa Roast", 
      "flavors": ["coffee", "maple", "syrup" ]
  },
  {
      "name": "Cafe African #5", 
      "brand": "Africa Roast", 
      "flavors": ["coffee", "southern", "croco", "maple" ]
  }
]
####
#### Updates a new coffee 
#### 
PATCH {{hostname}}/coffees/{{id}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

{
    "flavors": [
      "coffee",
      "maple",
      "orange"
    ]
}


####
#### Create a new coffee 
#### 
DELETE {{hostname}}/coffees/{{id}} HTTP/1.1
X-API-Key: 
Content-Type: application/json
